//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headstone.Framework.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrameworkModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Headstone.Framework.Models.Resources.FrameworkModels", typeof(FrameworkModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Entity_Created {
            get {
                return ResourceManager.GetString("Entity_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Entity_Status {
            get {
                return ResourceManager.GetString("Entity_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Entity_Updated {
            get {
                return ResourceManager.GetString("Entity_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Enumeration_AccountStatus_Active {
            get {
                return ResourceManager.GetString("Enumeration_AccountStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Enumeration_AccountStatus_Deleted {
            get {
                return ResourceManager.GetString("Enumeration_AccountStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed.
        /// </summary>
        public static string Enumeration_AccountStatus_Freezed {
            get {
                return ResourceManager.GetString("Enumeration_AccountStatus_Freezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        public static string Enumeration_AccountStatus_Passive {
            get {
                return ResourceManager.GetString("Enumeration_AccountStatus_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Enumeration_AccountStatus_Verified {
            get {
                return ResourceManager.GetString("Enumeration_AccountStatus_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Enumeration_EntityStatus_Active {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Enumeration_EntityStatus_Blocked {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Enumeration_EntityStatus_Deleted {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Enumeration_EntityStatus_Draft {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezed.
        /// </summary>
        public static string Enumeration_EntityStatus_Freezed {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Freezed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        public static string Enumeration_EntityStatus_Passive {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Enumeration_EntityStatus_Test {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Enumeration_EntityStatus_Unknown {
            get {
                return ResourceManager.GetString("Enumeration_EntityStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Enumeration_ResponseStatus_Approved {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string Enumeration_ResponseStatus_Declined {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Enumeration_ResponseStatus_Error {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Enumeration_ResponseStatus_Pending {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Enumeration_ResponseStatus_Timeout {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Enumeration_ResponseStatus_Unknown {
            get {
                return ResourceManager.GetString("Enumeration_ResponseStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvatarUrl.
        /// </summary>
        public static string Identity_ApplicationUser_AvatarUrl {
            get {
                return ResourceManager.GetString("Identity_ApplicationUser_AvatarUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Identity_ApplicationUser_Created {
            get {
                return ResourceManager.GetString("Identity_ApplicationUser_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Identity_ApplicationUser_FirstName {
            get {
                return ResourceManager.GetString("Identity_ApplicationUser_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        public static string Identity_ApplicationUser_LastLoginTime {
            get {
                return ResourceManager.GetString("Identity_ApplicationUser_LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Identity_ApplicationUser_LastName {
            get {
                return ResourceManager.GetString("Identity_ApplicationUser_LastName", resourceCulture);
            }
        }
    }
}
